export const punishmentList = [
    "Read the longest book on your TBR 😱",
    "Read a book you've started but put down 😬",
    "Read the book you've owned the longest 💀",
    "Read the lowest rated book on your TBR 😔",
    "Read a book you fear you've grown out of 🤔",
    "Read a book with a cover you *hate* 😤",
    "Read the book with the tiniest font 👀",
    "Read a book you've avoided for no good reason 😅",
    "Read a genre you rarely reach for 🤨",
    "Read a book you bought just because it was popular 📈",
    "Read a book with a title you can never remember 🤯",
    "Read a book a friend recommended... years ago 🙈",
    "Read a book by an intimidating author 📚🔥",
    "Read a book you've already unhauled and re-bought 🤡",
    "Read a book you *definitely* judged by its cover 😬",
    "Read the sequel to something you barely remember 🤷‍♀️",
    "Read a book that feels like homework 📝",
    "Read a book that's older than you 📜",
    "Unhaul the book you've been 'meaning to read' for five years 📦",
    "Unhaul the book you bought because it was $2 and you regret it 💸",
    "Unhaul the book with the ugliest cover 😬",
    "Unhaul the book you DNF'd... and you *know* you're not going back ❌",
    "Unhaul the book that makes you go 'meh' every time you see it 😑",
    "Unhaul the book you bought to impress someone who doesn't even read 🫠",
    "Unhaul the book whose genre you've completely outgrown 🕰️",
    "Unhaul the book you only bought because BookTube made you 🙄",
    "Unhaul the book you bought during a midlife identity crisis 🌀",
    "Unhaul the book you bought for the vibes and never even flipped through ✨",
];
